/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdCostRouteImport } from './routes/$projectId/cost'
import { Route as ProjectIdEvaluationRouteImport } from './routes/$projectId/evaluation'
import { Route as ProjectIdGuardrailsRouteImport } from './routes/$projectId/guardrails'
import { Route as ProjectIdKnowledgeBaseRouteImport } from './routes/$projectId/knowledge-base'
import { Route as ProjectIdMcpServersRouteImport } from './routes/$projectId/mcp-servers'
import { Route as ProjectIdMemoryRouteImport } from './routes/$projectId/memory'
import { Route as ProjectIdProfileRouteImport } from './routes/$projectId/profile'
import { Route as ProjectIdRuntimeRouteImport } from './routes/$projectId/runtime'
import { Route as ProjectIdRuntimePoliciesRouteImport } from './routes/$projectId/runtime-policies'
import { Route as ProjectIdSkillsRouteImport } from './routes/$projectId/skills'
import { Route as ProjectIdTracesRouteImport } from './routes/$projectId/traces'
import { Route as AuthSsoCompleteRouteImport } from './routes/auth/sso-complete'
import { Route as ProjectIdAccessPoliciesIndexRouteImport } from './routes/$projectId/access-policies/index'
import { Route as ProjectIdAccessPoliciesPolicyIdRouteImport } from './routes/$projectId/access-policies/$policyId'
import { Route as ProjectIdAgentGardenIndexRouteImport } from './routes/$projectId/agent-garden/index'
import { Route as ProjectIdAgentGardenAgentIdRouteImport } from './routes/$projectId/agent-garden/$agentId'
import { Route as ProjectIdAuditLogsIndexRouteImport } from './routes/$projectId/audit-logs/index'
import { Route as ProjectIdEvaluationIndexRouteImport } from './routes/$projectId/evaluation/index'
import { Route as ProjectIdEvaluationOverviewRouteImport } from './routes/$projectId/evaluation/overview'
import { Route as ProjectIdEvaluationSettingsRouteImport } from './routes/$projectId/evaluation/settings'
import { Route as ProjectIdEvaluationsIndexRouteImport } from './routes/$projectId/evaluations/index'
import { Route as ProjectIdEvaluationsNewRouteImport } from './routes/$projectId/evaluations/new'
import { Route as ProjectIdInstancesIndexRouteImport } from './routes/$projectId/instances/index'
import { Route as ProjectIdInstancesInstanceIdRouteImport } from './routes/$projectId/instances/$instanceId'
import { Route as ProjectIdRequestsIndexRouteImport } from './routes/$projectId/requests/index'
import { Route as ProjectIdRequestsNewRouteImport } from './routes/$projectId/requests/new'
import { Route as ProjectIdSettingIndexRouteImport } from './routes/$projectId/setting/index'
import { Route as ProjectIdEvaluationDatasetsIndexRouteImport } from './routes/$projectId/evaluation/datasets/index'
import { Route as ProjectIdEvaluationDatasetsDatasetIdRouteImport } from './routes/$projectId/evaluation/datasets/$datasetId'
import { Route as ProjectIdEvaluationReportsReportIdRouteImport } from './routes/$projectId/evaluation/reports/$reportId'
import { Route as ProjectIdEvaluationRunsIndexRouteImport } from './routes/$projectId/evaluation/runs/index'
import { Route as ProjectIdEvaluationRunsRunIdRouteImport } from './routes/$projectId/evaluation/runs/$runId'
import { Route as ProjectIdEvaluationRunsNewRouteImport } from './routes/$projectId/evaluation/runs/new'
import { Route as ProjectIdEvaluationTargetsIndexRouteImport } from './routes/$projectId/evaluation/targets/index'
import { Route as ProjectIdEvaluationTargetsTargetIdRouteImport } from './routes/$projectId/evaluation/targets/$targetId'
import { Route as ProjectIdEvaluationTracesIndexRouteImport } from './routes/$projectId/evaluation/traces/index'
import { Route as ProjectIdEvaluationTracesTraceIdRouteImport } from './routes/$projectId/evaluation/traces/$traceId'
import { Route as ProjectIdEvaluationsDatasetsDatasetIdRouteImport } from './routes/$projectId/evaluations/datasets/$datasetId'
import { Route as ProjectIdEvaluationsReportsReportIdRouteImport } from './routes/$projectId/evaluations/reports/$reportId'
import { Route as ProjectIdEvaluationsRunsRunIdRouteImport } from './routes/$projectId/evaluations/runs/$runId'
import { Route as ProjectIdEvaluationsTargetsTargetIdRouteImport } from './routes/$projectId/evaluations/targets/$targetId'
import { Route as ProjectIdSettingModelRoutingsRoutingIdRouteImport } from './routes/$projectId/setting/model-routings/$routingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdCostRoute = ProjectIdCostRouteImport.update({
  id: '/$projectId/cost',
  path: '/$projectId/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEvaluationRoute = ProjectIdEvaluationRouteImport.update({
  id: '/$projectId/evaluation',
  path: '/$projectId/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdGuardrailsRoute = ProjectIdGuardrailsRouteImport.update({
  id: '/$projectId/guardrails',
  path: '/$projectId/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdKnowledgeBaseRoute = ProjectIdKnowledgeBaseRouteImport.update({
  id: '/$projectId/knowledge-base',
  path: '/$projectId/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMcpServersRoute = ProjectIdMcpServersRouteImport.update({
  id: '/$projectId/mcp-servers',
  path: '/$projectId/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMemoryRoute = ProjectIdMemoryRouteImport.update({
  id: '/$projectId/memory',
  path: '/$projectId/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdProfileRoute = ProjectIdProfileRouteImport.update({
  id: '/$projectId/profile',
  path: '/$projectId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimeRoute = ProjectIdRuntimeRouteImport.update({
  id: '/$projectId/runtime',
  path: '/$projectId/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimePoliciesRoute =
  ProjectIdRuntimePoliciesRouteImport.update({
    id: '/$projectId/runtime-policies',
    path: '/$projectId/runtime-policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSkillsRoute = ProjectIdSkillsRouteImport.update({
  id: '/$projectId/skills',
  path: '/$projectId/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdTracesRoute = ProjectIdTracesRouteImport.update({
  id: '/$projectId/traces',
  path: '/$projectId/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCompleteRoute = AuthSsoCompleteRouteImport.update({
  id: '/auth/sso-complete',
  path: '/auth/sso-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdAccessPoliciesIndexRoute =
  ProjectIdAccessPoliciesIndexRouteImport.update({
    id: '/$projectId/access-policies/',
    path: '/$projectId/access-policies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAccessPoliciesPolicyIdRoute =
  ProjectIdAccessPoliciesPolicyIdRouteImport.update({
    id: '/$projectId/access-policies/$policyId',
    path: '/$projectId/access-policies/$policyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenIndexRoute =
  ProjectIdAgentGardenIndexRouteImport.update({
    id: '/$projectId/agent-garden/',
    path: '/$projectId/agent-garden/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenAgentIdRoute =
  ProjectIdAgentGardenAgentIdRouteImport.update({
    id: '/$projectId/agent-garden/$agentId',
    path: '/$projectId/agent-garden/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAuditLogsIndexRoute = ProjectIdAuditLogsIndexRouteImport.update({
  id: '/$projectId/audit-logs/',
  path: '/$projectId/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEvaluationIndexRoute =
  ProjectIdEvaluationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationOverviewRoute =
  ProjectIdEvaluationOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationSettingsRoute =
  ProjectIdEvaluationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationsIndexRoute =
  ProjectIdEvaluationsIndexRouteImport.update({
    id: '/$projectId/evaluations/',
    path: '/$projectId/evaluations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdEvaluationsNewRoute = ProjectIdEvaluationsNewRouteImport.update({
  id: '/$projectId/evaluations/new',
  path: '/$projectId/evaluations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesIndexRoute = ProjectIdInstancesIndexRouteImport.update({
  id: '/$projectId/instances/',
  path: '/$projectId/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesInstanceIdRoute =
  ProjectIdInstancesInstanceIdRouteImport.update({
    id: '/$projectId/instances/$instanceId',
    path: '/$projectId/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdRequestsIndexRoute = ProjectIdRequestsIndexRouteImport.update({
  id: '/$projectId/requests/',
  path: '/$projectId/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRequestsNewRoute = ProjectIdRequestsNewRouteImport.update({
  id: '/$projectId/requests/new',
  path: '/$projectId/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSettingIndexRoute = ProjectIdSettingIndexRouteImport.update({
  id: '/$projectId/setting/',
  path: '/$projectId/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEvaluationDatasetsIndexRoute =
  ProjectIdEvaluationDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationDatasetsDatasetIdRoute =
  ProjectIdEvaluationDatasetsDatasetIdRouteImport.update({
    id: '/datasets/$datasetId',
    path: '/datasets/$datasetId',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationReportsReportIdRoute =
  ProjectIdEvaluationReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationRunsIndexRoute =
  ProjectIdEvaluationRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationRunsRunIdRoute =
  ProjectIdEvaluationRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationRunsNewRoute =
  ProjectIdEvaluationRunsNewRouteImport.update({
    id: '/runs/new',
    path: '/runs/new',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationTargetsIndexRoute =
  ProjectIdEvaluationTargetsIndexRouteImport.update({
    id: '/targets/',
    path: '/targets/',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationTargetsTargetIdRoute =
  ProjectIdEvaluationTargetsTargetIdRouteImport.update({
    id: '/targets/$targetId',
    path: '/targets/$targetId',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationTracesIndexRoute =
  ProjectIdEvaluationTracesIndexRouteImport.update({
    id: '/traces/',
    path: '/traces/',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationTracesTraceIdRoute =
  ProjectIdEvaluationTracesTraceIdRouteImport.update({
    id: '/traces/$traceId',
    path: '/traces/$traceId',
    getParentRoute: () => ProjectIdEvaluationRoute,
  } as any)
const ProjectIdEvaluationsDatasetsDatasetIdRoute =
  ProjectIdEvaluationsDatasetsDatasetIdRouteImport.update({
    id: '/$projectId/evaluations/datasets/$datasetId',
    path: '/$projectId/evaluations/datasets/$datasetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdEvaluationsReportsReportIdRoute =
  ProjectIdEvaluationsReportsReportIdRouteImport.update({
    id: '/$projectId/evaluations/reports/$reportId',
    path: '/$projectId/evaluations/reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdEvaluationsRunsRunIdRoute =
  ProjectIdEvaluationsRunsRunIdRouteImport.update({
    id: '/$projectId/evaluations/runs/$runId',
    path: '/$projectId/evaluations/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdEvaluationsTargetsTargetIdRoute =
  ProjectIdEvaluationsTargetsTargetIdRouteImport.update({
    id: '/$projectId/evaluations/targets/$targetId',
    path: '/$projectId/evaluations/targets/$targetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSettingModelRoutingsRoutingIdRoute =
  ProjectIdSettingModelRoutingsRoutingIdRouteImport.update({
    id: '/$projectId/setting/model-routings/$routingId',
    path: '/$projectId/setting/model-routings/$routingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/evaluation': typeof ProjectIdEvaluationRouteWithChildren
  '/$projectId/guardrails': typeof ProjectIdGuardrailsRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/memory': typeof ProjectIdMemoryRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/evaluation/overview': typeof ProjectIdEvaluationOverviewRoute
  '/$projectId/evaluation/settings': typeof ProjectIdEvaluationSettingsRoute
  '/$projectId/evaluations/new': typeof ProjectIdEvaluationsNewRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/evaluation/': typeof ProjectIdEvaluationIndexRoute
  '/$projectId/evaluations/': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/evaluation/datasets/$datasetId': typeof ProjectIdEvaluationDatasetsDatasetIdRoute
  '/$projectId/evaluation/reports/$reportId': typeof ProjectIdEvaluationReportsReportIdRoute
  '/$projectId/evaluation/runs/$runId': typeof ProjectIdEvaluationRunsRunIdRoute
  '/$projectId/evaluation/runs/new': typeof ProjectIdEvaluationRunsNewRoute
  '/$projectId/evaluation/targets/$targetId': typeof ProjectIdEvaluationTargetsTargetIdRoute
  '/$projectId/evaluation/traces/$traceId': typeof ProjectIdEvaluationTracesTraceIdRoute
  '/$projectId/evaluations/datasets/$datasetId': typeof ProjectIdEvaluationsDatasetsDatasetIdRoute
  '/$projectId/evaluations/reports/$reportId': typeof ProjectIdEvaluationsReportsReportIdRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/targets/$targetId': typeof ProjectIdEvaluationsTargetsTargetIdRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
  '/$projectId/evaluation/datasets/': typeof ProjectIdEvaluationDatasetsIndexRoute
  '/$projectId/evaluation/runs/': typeof ProjectIdEvaluationRunsIndexRoute
  '/$projectId/evaluation/targets/': typeof ProjectIdEvaluationTargetsIndexRoute
  '/$projectId/evaluation/traces/': typeof ProjectIdEvaluationTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/guardrails': typeof ProjectIdGuardrailsRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/memory': typeof ProjectIdMemoryRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/evaluation/overview': typeof ProjectIdEvaluationOverviewRoute
  '/$projectId/evaluation/settings': typeof ProjectIdEvaluationSettingsRoute
  '/$projectId/evaluations/new': typeof ProjectIdEvaluationsNewRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/evaluation': typeof ProjectIdEvaluationIndexRoute
  '/$projectId/evaluations': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/instances': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting': typeof ProjectIdSettingIndexRoute
  '/$projectId/evaluation/datasets/$datasetId': typeof ProjectIdEvaluationDatasetsDatasetIdRoute
  '/$projectId/evaluation/reports/$reportId': typeof ProjectIdEvaluationReportsReportIdRoute
  '/$projectId/evaluation/runs/$runId': typeof ProjectIdEvaluationRunsRunIdRoute
  '/$projectId/evaluation/runs/new': typeof ProjectIdEvaluationRunsNewRoute
  '/$projectId/evaluation/targets/$targetId': typeof ProjectIdEvaluationTargetsTargetIdRoute
  '/$projectId/evaluation/traces/$traceId': typeof ProjectIdEvaluationTracesTraceIdRoute
  '/$projectId/evaluations/datasets/$datasetId': typeof ProjectIdEvaluationsDatasetsDatasetIdRoute
  '/$projectId/evaluations/reports/$reportId': typeof ProjectIdEvaluationsReportsReportIdRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/targets/$targetId': typeof ProjectIdEvaluationsTargetsTargetIdRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
  '/$projectId/evaluation/datasets': typeof ProjectIdEvaluationDatasetsIndexRoute
  '/$projectId/evaluation/runs': typeof ProjectIdEvaluationRunsIndexRoute
  '/$projectId/evaluation/targets': typeof ProjectIdEvaluationTargetsIndexRoute
  '/$projectId/evaluation/traces': typeof ProjectIdEvaluationTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/evaluation': typeof ProjectIdEvaluationRouteWithChildren
  '/$projectId/guardrails': typeof ProjectIdGuardrailsRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/memory': typeof ProjectIdMemoryRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/evaluation/overview': typeof ProjectIdEvaluationOverviewRoute
  '/$projectId/evaluation/settings': typeof ProjectIdEvaluationSettingsRoute
  '/$projectId/evaluations/new': typeof ProjectIdEvaluationsNewRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/evaluation/': typeof ProjectIdEvaluationIndexRoute
  '/$projectId/evaluations/': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/evaluation/datasets/$datasetId': typeof ProjectIdEvaluationDatasetsDatasetIdRoute
  '/$projectId/evaluation/reports/$reportId': typeof ProjectIdEvaluationReportsReportIdRoute
  '/$projectId/evaluation/runs/$runId': typeof ProjectIdEvaluationRunsRunIdRoute
  '/$projectId/evaluation/runs/new': typeof ProjectIdEvaluationRunsNewRoute
  '/$projectId/evaluation/targets/$targetId': typeof ProjectIdEvaluationTargetsTargetIdRoute
  '/$projectId/evaluation/traces/$traceId': typeof ProjectIdEvaluationTracesTraceIdRoute
  '/$projectId/evaluations/datasets/$datasetId': typeof ProjectIdEvaluationsDatasetsDatasetIdRoute
  '/$projectId/evaluations/reports/$reportId': typeof ProjectIdEvaluationsReportsReportIdRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/targets/$targetId': typeof ProjectIdEvaluationsTargetsTargetIdRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
  '/$projectId/evaluation/datasets/': typeof ProjectIdEvaluationDatasetsIndexRoute
  '/$projectId/evaluation/runs/': typeof ProjectIdEvaluationRunsIndexRoute
  '/$projectId/evaluation/targets/': typeof ProjectIdEvaluationTargetsIndexRoute
  '/$projectId/evaluation/traces/': typeof ProjectIdEvaluationTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/evaluation'
    | '/$projectId/guardrails'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/memory'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/evaluation/overview'
    | '/$projectId/evaluation/settings'
    | '/$projectId/evaluations/new'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/evaluation/'
    | '/$projectId/evaluations/'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/evaluation/datasets/$datasetId'
    | '/$projectId/evaluation/reports/$reportId'
    | '/$projectId/evaluation/runs/$runId'
    | '/$projectId/evaluation/runs/new'
    | '/$projectId/evaluation/targets/$targetId'
    | '/$projectId/evaluation/traces/$traceId'
    | '/$projectId/evaluations/datasets/$datasetId'
    | '/$projectId/evaluations/reports/$reportId'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/targets/$targetId'
    | '/$projectId/setting/model-routings/$routingId'
    | '/$projectId/evaluation/datasets/'
    | '/$projectId/evaluation/runs/'
    | '/$projectId/evaluation/targets/'
    | '/$projectId/evaluation/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/guardrails'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/memory'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/evaluation/overview'
    | '/$projectId/evaluation/settings'
    | '/$projectId/evaluations/new'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies'
    | '/$projectId/agent-garden'
    | '/$projectId/audit-logs'
    | '/$projectId/evaluation'
    | '/$projectId/evaluations'
    | '/$projectId/instances'
    | '/$projectId/requests'
    | '/$projectId/setting'
    | '/$projectId/evaluation/datasets/$datasetId'
    | '/$projectId/evaluation/reports/$reportId'
    | '/$projectId/evaluation/runs/$runId'
    | '/$projectId/evaluation/runs/new'
    | '/$projectId/evaluation/targets/$targetId'
    | '/$projectId/evaluation/traces/$traceId'
    | '/$projectId/evaluations/datasets/$datasetId'
    | '/$projectId/evaluations/reports/$reportId'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/targets/$targetId'
    | '/$projectId/setting/model-routings/$routingId'
    | '/$projectId/evaluation/datasets'
    | '/$projectId/evaluation/runs'
    | '/$projectId/evaluation/targets'
    | '/$projectId/evaluation/traces'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/evaluation'
    | '/$projectId/guardrails'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/memory'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/evaluation/overview'
    | '/$projectId/evaluation/settings'
    | '/$projectId/evaluations/new'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/evaluation/'
    | '/$projectId/evaluations/'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/evaluation/datasets/$datasetId'
    | '/$projectId/evaluation/reports/$reportId'
    | '/$projectId/evaluation/runs/$runId'
    | '/$projectId/evaluation/runs/new'
    | '/$projectId/evaluation/targets/$targetId'
    | '/$projectId/evaluation/traces/$traceId'
    | '/$projectId/evaluations/datasets/$datasetId'
    | '/$projectId/evaluations/reports/$reportId'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/targets/$targetId'
    | '/$projectId/setting/model-routings/$routingId'
    | '/$projectId/evaluation/datasets/'
    | '/$projectId/evaluation/runs/'
    | '/$projectId/evaluation/targets/'
    | '/$projectId/evaluation/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectIdCostRoute: typeof ProjectIdCostRoute
  ProjectIdEvaluationRoute: typeof ProjectIdEvaluationRouteWithChildren
  ProjectIdGuardrailsRoute: typeof ProjectIdGuardrailsRoute
  ProjectIdKnowledgeBaseRoute: typeof ProjectIdKnowledgeBaseRoute
  ProjectIdMcpServersRoute: typeof ProjectIdMcpServersRoute
  ProjectIdMemoryRoute: typeof ProjectIdMemoryRoute
  ProjectIdProfileRoute: typeof ProjectIdProfileRoute
  ProjectIdRuntimeRoute: typeof ProjectIdRuntimeRoute
  ProjectIdRuntimePoliciesRoute: typeof ProjectIdRuntimePoliciesRoute
  ProjectIdSkillsRoute: typeof ProjectIdSkillsRoute
  ProjectIdTracesRoute: typeof ProjectIdTracesRoute
  AuthSsoCompleteRoute: typeof AuthSsoCompleteRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdAccessPoliciesPolicyIdRoute: typeof ProjectIdAccessPoliciesPolicyIdRoute
  ProjectIdAgentGardenAgentIdRoute: typeof ProjectIdAgentGardenAgentIdRoute
  ProjectIdEvaluationsNewRoute: typeof ProjectIdEvaluationsNewRoute
  ProjectIdInstancesInstanceIdRoute: typeof ProjectIdInstancesInstanceIdRoute
  ProjectIdRequestsNewRoute: typeof ProjectIdRequestsNewRoute
  ProjectIdAccessPoliciesIndexRoute: typeof ProjectIdAccessPoliciesIndexRoute
  ProjectIdAgentGardenIndexRoute: typeof ProjectIdAgentGardenIndexRoute
  ProjectIdAuditLogsIndexRoute: typeof ProjectIdAuditLogsIndexRoute
  ProjectIdEvaluationsIndexRoute: typeof ProjectIdEvaluationsIndexRoute
  ProjectIdInstancesIndexRoute: typeof ProjectIdInstancesIndexRoute
  ProjectIdRequestsIndexRoute: typeof ProjectIdRequestsIndexRoute
  ProjectIdSettingIndexRoute: typeof ProjectIdSettingIndexRoute
  ProjectIdEvaluationsDatasetsDatasetIdRoute: typeof ProjectIdEvaluationsDatasetsDatasetIdRoute
  ProjectIdEvaluationsReportsReportIdRoute: typeof ProjectIdEvaluationsReportsReportIdRoute
  ProjectIdEvaluationsRunsRunIdRoute: typeof ProjectIdEvaluationsRunsRunIdRoute
  ProjectIdEvaluationsTargetsTargetIdRoute: typeof ProjectIdEvaluationsTargetsTargetIdRoute
  ProjectIdSettingModelRoutingsRoutingIdRoute: typeof ProjectIdSettingModelRoutingsRoutingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/cost': {
      id: '/$projectId/cost'
      path: '/$projectId/cost'
      fullPath: '/$projectId/cost'
      preLoaderRoute: typeof ProjectIdCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluation': {
      id: '/$projectId/evaluation'
      path: '/$projectId/evaluation'
      fullPath: '/$projectId/evaluation'
      preLoaderRoute: typeof ProjectIdEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/guardrails': {
      id: '/$projectId/guardrails'
      path: '/$projectId/guardrails'
      fullPath: '/$projectId/guardrails'
      preLoaderRoute: typeof ProjectIdGuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/knowledge-base': {
      id: '/$projectId/knowledge-base'
      path: '/$projectId/knowledge-base'
      fullPath: '/$projectId/knowledge-base'
      preLoaderRoute: typeof ProjectIdKnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/mcp-servers': {
      id: '/$projectId/mcp-servers'
      path: '/$projectId/mcp-servers'
      fullPath: '/$projectId/mcp-servers'
      preLoaderRoute: typeof ProjectIdMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/memory': {
      id: '/$projectId/memory'
      path: '/$projectId/memory'
      fullPath: '/$projectId/memory'
      preLoaderRoute: typeof ProjectIdMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/profile': {
      id: '/$projectId/profile'
      path: '/$projectId/profile'
      fullPath: '/$projectId/profile'
      preLoaderRoute: typeof ProjectIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime': {
      id: '/$projectId/runtime'
      path: '/$projectId/runtime'
      fullPath: '/$projectId/runtime'
      preLoaderRoute: typeof ProjectIdRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime-policies': {
      id: '/$projectId/runtime-policies'
      path: '/$projectId/runtime-policies'
      fullPath: '/$projectId/runtime-policies'
      preLoaderRoute: typeof ProjectIdRuntimePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/skills': {
      id: '/$projectId/skills'
      path: '/$projectId/skills'
      fullPath: '/$projectId/skills'
      preLoaderRoute: typeof ProjectIdSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/traces': {
      id: '/$projectId/traces'
      path: '/$projectId/traces'
      fullPath: '/$projectId/traces'
      preLoaderRoute: typeof ProjectIdTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-complete': {
      id: '/auth/sso-complete'
      path: '/auth/sso-complete'
      fullPath: '/auth/sso-complete'
      preLoaderRoute: typeof AuthSsoCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/': {
      id: '/$projectId/access-policies/'
      path: '/$projectId/access-policies'
      fullPath: '/$projectId/access-policies/'
      preLoaderRoute: typeof ProjectIdAccessPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/$policyId': {
      id: '/$projectId/access-policies/$policyId'
      path: '/$projectId/access-policies/$policyId'
      fullPath: '/$projectId/access-policies/$policyId'
      preLoaderRoute: typeof ProjectIdAccessPoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/': {
      id: '/$projectId/agent-garden/'
      path: '/$projectId/agent-garden'
      fullPath: '/$projectId/agent-garden/'
      preLoaderRoute: typeof ProjectIdAgentGardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/$agentId': {
      id: '/$projectId/agent-garden/$agentId'
      path: '/$projectId/agent-garden/$agentId'
      fullPath: '/$projectId/agent-garden/$agentId'
      preLoaderRoute: typeof ProjectIdAgentGardenAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/audit-logs/': {
      id: '/$projectId/audit-logs/'
      path: '/$projectId/audit-logs'
      fullPath: '/$projectId/audit-logs/'
      preLoaderRoute: typeof ProjectIdAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluation/': {
      id: '/$projectId/evaluation/'
      path: '/'
      fullPath: '/$projectId/evaluation/'
      preLoaderRoute: typeof ProjectIdEvaluationIndexRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/overview': {
      id: '/$projectId/evaluation/overview'
      path: '/overview'
      fullPath: '/$projectId/evaluation/overview'
      preLoaderRoute: typeof ProjectIdEvaluationOverviewRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/settings': {
      id: '/$projectId/evaluation/settings'
      path: '/settings'
      fullPath: '/$projectId/evaluation/settings'
      preLoaderRoute: typeof ProjectIdEvaluationSettingsRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluations/': {
      id: '/$projectId/evaluations/'
      path: '/$projectId/evaluations'
      fullPath: '/$projectId/evaluations/'
      preLoaderRoute: typeof ProjectIdEvaluationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluations/new': {
      id: '/$projectId/evaluations/new'
      path: '/$projectId/evaluations/new'
      fullPath: '/$projectId/evaluations/new'
      preLoaderRoute: typeof ProjectIdEvaluationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/': {
      id: '/$projectId/instances/'
      path: '/$projectId/instances'
      fullPath: '/$projectId/instances/'
      preLoaderRoute: typeof ProjectIdInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/$instanceId': {
      id: '/$projectId/instances/$instanceId'
      path: '/$projectId/instances/$instanceId'
      fullPath: '/$projectId/instances/$instanceId'
      preLoaderRoute: typeof ProjectIdInstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/': {
      id: '/$projectId/requests/'
      path: '/$projectId/requests'
      fullPath: '/$projectId/requests/'
      preLoaderRoute: typeof ProjectIdRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/new': {
      id: '/$projectId/requests/new'
      path: '/$projectId/requests/new'
      fullPath: '/$projectId/requests/new'
      preLoaderRoute: typeof ProjectIdRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/': {
      id: '/$projectId/setting/'
      path: '/$projectId/setting'
      fullPath: '/$projectId/setting/'
      preLoaderRoute: typeof ProjectIdSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluation/datasets/': {
      id: '/$projectId/evaluation/datasets/'
      path: '/datasets'
      fullPath: '/$projectId/evaluation/datasets/'
      preLoaderRoute: typeof ProjectIdEvaluationDatasetsIndexRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/datasets/$datasetId': {
      id: '/$projectId/evaluation/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/$projectId/evaluation/datasets/$datasetId'
      preLoaderRoute: typeof ProjectIdEvaluationDatasetsDatasetIdRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/reports/$reportId': {
      id: '/$projectId/evaluation/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/$projectId/evaluation/reports/$reportId'
      preLoaderRoute: typeof ProjectIdEvaluationReportsReportIdRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/runs/': {
      id: '/$projectId/evaluation/runs/'
      path: '/runs'
      fullPath: '/$projectId/evaluation/runs/'
      preLoaderRoute: typeof ProjectIdEvaluationRunsIndexRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/runs/$runId': {
      id: '/$projectId/evaluation/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/$projectId/evaluation/runs/$runId'
      preLoaderRoute: typeof ProjectIdEvaluationRunsRunIdRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/runs/new': {
      id: '/$projectId/evaluation/runs/new'
      path: '/runs/new'
      fullPath: '/$projectId/evaluation/runs/new'
      preLoaderRoute: typeof ProjectIdEvaluationRunsNewRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/targets/': {
      id: '/$projectId/evaluation/targets/'
      path: '/targets'
      fullPath: '/$projectId/evaluation/targets/'
      preLoaderRoute: typeof ProjectIdEvaluationTargetsIndexRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/targets/$targetId': {
      id: '/$projectId/evaluation/targets/$targetId'
      path: '/targets/$targetId'
      fullPath: '/$projectId/evaluation/targets/$targetId'
      preLoaderRoute: typeof ProjectIdEvaluationTargetsTargetIdRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/traces/': {
      id: '/$projectId/evaluation/traces/'
      path: '/traces'
      fullPath: '/$projectId/evaluation/traces/'
      preLoaderRoute: typeof ProjectIdEvaluationTracesIndexRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluation/traces/$traceId': {
      id: '/$projectId/evaluation/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/$projectId/evaluation/traces/$traceId'
      preLoaderRoute: typeof ProjectIdEvaluationTracesTraceIdRouteImport
      parentRoute: typeof ProjectIdEvaluationRoute
    }
    '/$projectId/evaluations/datasets/$datasetId': {
      id: '/$projectId/evaluations/datasets/$datasetId'
      path: '/$projectId/evaluations/datasets/$datasetId'
      fullPath: '/$projectId/evaluations/datasets/$datasetId'
      preLoaderRoute: typeof ProjectIdEvaluationsDatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluations/reports/$reportId': {
      id: '/$projectId/evaluations/reports/$reportId'
      path: '/$projectId/evaluations/reports/$reportId'
      fullPath: '/$projectId/evaluations/reports/$reportId'
      preLoaderRoute: typeof ProjectIdEvaluationsReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluations/runs/$runId': {
      id: '/$projectId/evaluations/runs/$runId'
      path: '/$projectId/evaluations/runs/$runId'
      fullPath: '/$projectId/evaluations/runs/$runId'
      preLoaderRoute: typeof ProjectIdEvaluationsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluations/targets/$targetId': {
      id: '/$projectId/evaluations/targets/$targetId'
      path: '/$projectId/evaluations/targets/$targetId'
      fullPath: '/$projectId/evaluations/targets/$targetId'
      preLoaderRoute: typeof ProjectIdEvaluationsTargetsTargetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/model-routings/$routingId': {
      id: '/$projectId/setting/model-routings/$routingId'
      path: '/$projectId/setting/model-routings/$routingId'
      fullPath: '/$projectId/setting/model-routings/$routingId'
      preLoaderRoute: typeof ProjectIdSettingModelRoutingsRoutingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectIdEvaluationRouteChildren {
  ProjectIdEvaluationOverviewRoute: typeof ProjectIdEvaluationOverviewRoute
  ProjectIdEvaluationSettingsRoute: typeof ProjectIdEvaluationSettingsRoute
  ProjectIdEvaluationIndexRoute: typeof ProjectIdEvaluationIndexRoute
  ProjectIdEvaluationDatasetsDatasetIdRoute: typeof ProjectIdEvaluationDatasetsDatasetIdRoute
  ProjectIdEvaluationReportsReportIdRoute: typeof ProjectIdEvaluationReportsReportIdRoute
  ProjectIdEvaluationRunsRunIdRoute: typeof ProjectIdEvaluationRunsRunIdRoute
  ProjectIdEvaluationRunsNewRoute: typeof ProjectIdEvaluationRunsNewRoute
  ProjectIdEvaluationTargetsTargetIdRoute: typeof ProjectIdEvaluationTargetsTargetIdRoute
  ProjectIdEvaluationTracesTraceIdRoute: typeof ProjectIdEvaluationTracesTraceIdRoute
  ProjectIdEvaluationDatasetsIndexRoute: typeof ProjectIdEvaluationDatasetsIndexRoute
  ProjectIdEvaluationRunsIndexRoute: typeof ProjectIdEvaluationRunsIndexRoute
  ProjectIdEvaluationTargetsIndexRoute: typeof ProjectIdEvaluationTargetsIndexRoute
  ProjectIdEvaluationTracesIndexRoute: typeof ProjectIdEvaluationTracesIndexRoute
}

const ProjectIdEvaluationRouteChildren: ProjectIdEvaluationRouteChildren = {
  ProjectIdEvaluationOverviewRoute: ProjectIdEvaluationOverviewRoute,
  ProjectIdEvaluationSettingsRoute: ProjectIdEvaluationSettingsRoute,
  ProjectIdEvaluationIndexRoute: ProjectIdEvaluationIndexRoute,
  ProjectIdEvaluationDatasetsDatasetIdRoute:
    ProjectIdEvaluationDatasetsDatasetIdRoute,
  ProjectIdEvaluationReportsReportIdRoute:
    ProjectIdEvaluationReportsReportIdRoute,
  ProjectIdEvaluationRunsRunIdRoute: ProjectIdEvaluationRunsRunIdRoute,
  ProjectIdEvaluationRunsNewRoute: ProjectIdEvaluationRunsNewRoute,
  ProjectIdEvaluationTargetsTargetIdRoute:
    ProjectIdEvaluationTargetsTargetIdRoute,
  ProjectIdEvaluationTracesTraceIdRoute: ProjectIdEvaluationTracesTraceIdRoute,
  ProjectIdEvaluationDatasetsIndexRoute: ProjectIdEvaluationDatasetsIndexRoute,
  ProjectIdEvaluationRunsIndexRoute: ProjectIdEvaluationRunsIndexRoute,
  ProjectIdEvaluationTargetsIndexRoute: ProjectIdEvaluationTargetsIndexRoute,
  ProjectIdEvaluationTracesIndexRoute: ProjectIdEvaluationTracesIndexRoute,
}

const ProjectIdEvaluationRouteWithChildren =
  ProjectIdEvaluationRoute._addFileChildren(ProjectIdEvaluationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectIdCostRoute: ProjectIdCostRoute,
  ProjectIdEvaluationRoute: ProjectIdEvaluationRouteWithChildren,
  ProjectIdGuardrailsRoute: ProjectIdGuardrailsRoute,
  ProjectIdKnowledgeBaseRoute: ProjectIdKnowledgeBaseRoute,
  ProjectIdMcpServersRoute: ProjectIdMcpServersRoute,
  ProjectIdMemoryRoute: ProjectIdMemoryRoute,
  ProjectIdProfileRoute: ProjectIdProfileRoute,
  ProjectIdRuntimeRoute: ProjectIdRuntimeRoute,
  ProjectIdRuntimePoliciesRoute: ProjectIdRuntimePoliciesRoute,
  ProjectIdSkillsRoute: ProjectIdSkillsRoute,
  ProjectIdTracesRoute: ProjectIdTracesRoute,
  AuthSsoCompleteRoute: AuthSsoCompleteRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdAccessPoliciesPolicyIdRoute: ProjectIdAccessPoliciesPolicyIdRoute,
  ProjectIdAgentGardenAgentIdRoute: ProjectIdAgentGardenAgentIdRoute,
  ProjectIdEvaluationsNewRoute: ProjectIdEvaluationsNewRoute,
  ProjectIdInstancesInstanceIdRoute: ProjectIdInstancesInstanceIdRoute,
  ProjectIdRequestsNewRoute: ProjectIdRequestsNewRoute,
  ProjectIdAccessPoliciesIndexRoute: ProjectIdAccessPoliciesIndexRoute,
  ProjectIdAgentGardenIndexRoute: ProjectIdAgentGardenIndexRoute,
  ProjectIdAuditLogsIndexRoute: ProjectIdAuditLogsIndexRoute,
  ProjectIdEvaluationsIndexRoute: ProjectIdEvaluationsIndexRoute,
  ProjectIdInstancesIndexRoute: ProjectIdInstancesIndexRoute,
  ProjectIdRequestsIndexRoute: ProjectIdRequestsIndexRoute,
  ProjectIdSettingIndexRoute: ProjectIdSettingIndexRoute,
  ProjectIdEvaluationsDatasetsDatasetIdRoute:
    ProjectIdEvaluationsDatasetsDatasetIdRoute,
  ProjectIdEvaluationsReportsReportIdRoute:
    ProjectIdEvaluationsReportsReportIdRoute,
  ProjectIdEvaluationsRunsRunIdRoute: ProjectIdEvaluationsRunsRunIdRoute,
  ProjectIdEvaluationsTargetsTargetIdRoute:
    ProjectIdEvaluationsTargetsTargetIdRoute,
  ProjectIdSettingModelRoutingsRoutingIdRoute:
    ProjectIdSettingModelRoutingsRoutingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
