/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SandboxesRouteImport } from './routes/sandboxes'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as MonitorPerformanceRouteImport } from './routes/monitor/performance'
import { Route as MonitorCostRouteImport } from './routes/monitor/cost'
import { Route as MonitorAuditRouteImport } from './routes/monitor/audit'
import { Route as AuthSsoCompleteRouteImport } from './routes/auth/sso-complete'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesRoute = SandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorPerformanceRoute = MonitorPerformanceRouteImport.update({
  id: '/monitor/performance',
  path: '/monitor/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorCostRoute = MonitorCostRouteImport.update({
  id: '/monitor/cost',
  path: '/monitor/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorAuditRoute = MonitorAuditRouteImport.update({
  id: '/monitor/audit',
  path: '/monitor/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCompleteRoute = AuthSsoCompleteRouteImport.update({
  id: '/auth/sso-complete',
  path: '/auth/sso-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/monitor/audit': typeof MonitorAuditRoute
  '/monitor/cost': typeof MonitorCostRoute
  '/monitor/performance': typeof MonitorPerformanceRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/monitor/audit': typeof MonitorAuditRoute
  '/monitor/cost': typeof MonitorCostRoute
  '/monitor/performance': typeof MonitorPerformanceRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/monitor/audit': typeof MonitorAuditRoute
  '/monitor/cost': typeof MonitorCostRoute
  '/monitor/performance': typeof MonitorPerformanceRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/instances'
    | '/login'
    | '/providers'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/monitor/audit'
    | '/monitor/cost'
    | '/monitor/performance'
    | '/requests/new'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/instances'
    | '/login'
    | '/providers'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/monitor/audit'
    | '/monitor/cost'
    | '/monitor/performance'
    | '/requests/new'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/instances'
    | '/login'
    | '/providers'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/monitor/audit'
    | '/monitor/cost'
    | '/monitor/performance'
    | '/requests/new'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InstancesRoute: typeof InstancesRoute
  LoginRoute: typeof LoginRoute
  ProvidersRoute: typeof ProvidersRoute
  SandboxesRoute: typeof SandboxesRoute
  SkillsRoute: typeof SkillsRoute
  TicketsRoute: typeof TicketsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AuthSsoCompleteRoute: typeof AuthSsoCompleteRoute
  MonitorAuditRoute: typeof MonitorAuditRoute
  MonitorCostRoute: typeof MonitorCostRoute
  MonitorPerformanceRoute: typeof MonitorPerformanceRoute
  RequestsNewRoute: typeof RequestsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes': {
      id: '/sandboxes'
      path: '/sandboxes'
      fullPath: '/sandboxes'
      preLoaderRoute: typeof SandboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/performance': {
      id: '/monitor/performance'
      path: '/monitor/performance'
      fullPath: '/monitor/performance'
      preLoaderRoute: typeof MonitorPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/cost': {
      id: '/monitor/cost'
      path: '/monitor/cost'
      fullPath: '/monitor/cost'
      preLoaderRoute: typeof MonitorCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/audit': {
      id: '/monitor/audit'
      path: '/monitor/audit'
      fullPath: '/monitor/audit'
      preLoaderRoute: typeof MonitorAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-complete': {
      id: '/auth/sso-complete'
      path: '/auth/sso-complete'
      fullPath: '/auth/sso-complete'
      preLoaderRoute: typeof AuthSsoCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InstancesRoute: InstancesRoute,
  LoginRoute: LoginRoute,
  ProvidersRoute: ProvidersRoute,
  SandboxesRoute: SandboxesRoute,
  SkillsRoute: SkillsRoute,
  TicketsRoute: TicketsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  AuthSsoCompleteRoute: AuthSsoCompleteRoute,
  MonitorAuditRoute: MonitorAuditRoute,
  MonitorCostRoute: MonitorCostRoute,
  MonitorPerformanceRoute: MonitorPerformanceRoute,
  RequestsNewRoute: RequestsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
