import { useMemo, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useEvaluationState } from "../mock-provider";
import { reportComparisonView } from "./report-view-model";

export function ReportComparison({ reportId }: { reportId: string }) {
  const state = useEvaluationState(); const current = state.reports.find((item) => item.id === reportId);
  const candidates = useMemo(() => state.reports.filter((item) => item.targetId === current?.targetId && item.id !== reportId).sort((a,b) => b.createdAt.localeCompare(a.createdAt)), [current?.targetId, reportId, state.reports]);
  const [selected, setSelected] = useState(candidates[0]?.id ?? "");
  if (!current || !selected) return <Card><CardHeader><CardTitle>Comparison</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">No prior Report exists for this Target.</p></CardContent></Card>;
  const view = reportComparisonView(state, selected, reportId);
  return <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><CardTitle>Comparison</CardTitle><select value={selected} onChange={(event) => setSelected(event.target.value)} aria-label="Baseline Report" className="h-9 rounded-md border bg-background px-3 text-sm">{candidates.map((item) => <option key={item.id} value={item.id}>{new Date(item.createdAt).toLocaleString()} · {item.metrics.passRate}%</option>)}</select></div></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Delta label="Shared-case pass rate" value={`${view.passRateDelta > 0 ? '+' : ''}${view.passRateDelta}%`} direction={view.passRateDelta} /><Delta label="Evaluation cost" value={`${view.costDelta > 0 ? '+' : ''}$${view.costDelta.toFixed(4)}`} direction={-view.costDelta} /><Delta label="Shared Cases" value={String(view.sharedCaseIds.length)} direction={0} /></div><div className="grid gap-4 md:grid-cols-2"><ComparisonList label="Regressions" values={view.regressions} tone="bad" /><ComparisonList label="Resolved failures" values={view.resolvedFailures} tone="good" /><ComparisonList label="Unchanged failures" values={view.unchangedFailures} /><ComparisonList label="Added / removed" values={[...view.addedCases.map((item) => `+ ${item}`), ...view.removedCases.map((item) => `− ${item}`)]} /></div><div className="rounded-md border bg-muted/20 p-4 text-sm"><div className="flex items-center justify-between"><span className="font-medium">Target configuration diff</span><Badge variant="outline">{view.configurationChanged ? "Changed" : "Unchanged"}</Badge></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><p><span className="text-muted-foreground">Baseline:</span> r{view.baselineRevision?.revision ?? "?"} · {view.baselineRevision?.model.name ?? "Not available"}</p><p><span className="text-muted-foreground">Current:</span> r{view.currentRevision?.revision ?? "?"} · {view.currentRevision?.model.name ?? "Not available"}</p></div></div><p className="text-xs text-muted-foreground">Judge, tool-state, and token deltas use the same shared Case IDs above; open Test Results for the underlying per-Case evidence.</p></CardContent></Card>;
}
function Delta({ direction, label, value }: { direction: number; label: string; value: string }) { const Icon = direction > 0 ? ArrowUp : direction < 0 ? ArrowDown : ArrowRight; return <div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 flex items-center gap-2 text-xl font-semibold"><Icon className="size-4" />{value}</p></div>; }
function ComparisonList({ label, tone, values }: { label: string; tone?: "bad" | "good"; values: string[] }) { return <div><p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><div className="flex min-h-8 flex-wrap gap-1.5">{values.length ? values.map((item) => <Badge key={item} variant={tone === "bad" ? "destructive" : "outline"} className={tone === "good" ? "border-emerald-300 text-emerald-700" : undefined}>{item}</Badge>) : <span className="text-sm text-muted-foreground">None</span>}</div></div>; }
